// seeds/002_vector_integral_25_questions.js
const bcrypt = require('bcryptjs');

exports.seed = async function(knex) {
  const now = new Date();
  const createdBy = 1; // Assuming admin user ID is 1

  // Insert 25 questions (vector and integral calculus mix)
  const questions = [
    // Vector questions
    { id: 101, exam_id: 1, stem: 'Find the magnitude of the vector \\( \\vec{a} = 3\\hat{i} - 2\\hat{j} + 6\\hat{k} \\).', difficulty: 'easy', created_by: createdBy, status: '1', created_at: now },
    { id: 102, exam_id: 1, stem: 'Let \\( \\vec{a}, \\vec{b}, \\vec{c} \\) be non-coplanar vectors. If vectors \\( \\overrightarrow{AB}, \\overrightarrow{AC}, \\overrightarrow{AD} \\) are coplanar, find the value of \\( \\lambda \\) given points.', difficulty: 'hard', created_by: createdBy, status: '1', created_at: now },
    { id: 103, exam_id: 1, stem: 'Which among the following is a vector quantity? (a) Mass (b) Length (c) Speed (d) Impulse', difficulty: 'easy', created_by: createdBy, status: '1', created_at: now },
    { id: 104, exam_id: 1, stem: 'If \\( \\vec{a}, \\vec{b}, \\vec{c} \\) are coplanar, then scalar triple product \\( [\\vec{a}\\ \\vec{b}\\ \\vec{c}] = 0 \\). True or False?', difficulty: 'medium', created_by: createdBy, status: '1', created_at: now },
    { id: 105, exam_id: 1, stem: 'Find the angle between vectors \\( \\vec{a} = 2\\hat{i} + 3\\hat{j} - \\hat{k} \\) and \\( \\vec{b} = -\\hat{i} + 4\\hat{j} + 5\\hat{k} \\).', difficulty: 'medium', created_by: createdBy, status: '1', created_at: now },
    { id: 106, exam_id: 1, stem: 'Find the area of the triangle with vertices (1,2,3), (4,0,1), and (3,3,2).', difficulty: 'medium', created_by: createdBy, status: '1', created_at: now },
    { id: 115, exam_id: 1, stem: 'Determine the point on the line through A(1,2,3) and B(4,5,6) closest to origin.', difficulty: 'hard', created_by: createdBy, status: '1', created_at: now },
    { id: 116, exam_id: 1, stem: 'For vectors \\( |\\vec{a}|=2, |\\vec{b}|=3 \\) and angle between them 60°, find \\( |\\vec{a} + \\vec{b}| \\).', difficulty: 'easy', created_by: createdBy, status: '1', created_at: now },
    { id: 122, exam_id: 1, stem: 'Find the volume of the parallelepiped formed by vectors \\( \\vec{a} = \\hat{i} + 2\\hat{j} \\), \\( \\vec{b} = 3\\hat{i} - \\hat{j} \\), \\( \\vec{c} = 4\\hat{k} \\).', difficulty: 'hard', created_by: createdBy, status: '1', created_at: now },
    { id: 123, exam_id: 1, stem: 'For vector \\( \\vec{a} = \\hat{i} - 2\\hat{j} + 3\\hat{k} \\), find the unit vector perpendicular to \\( \\vec{a} \\).', difficulty: 'hard', created_by: createdBy, status: '1', created_at: now },
    { id: 119, exam_id: 1, stem: 'Find the gradient vector of function \\( f(x,y,z) = xyz \\) at point (1,2,3).', difficulty: 'medium', created_by: createdBy, status: '1', created_at: now },
    { id: 120, exam_id: 1, stem: 'Evaluate limit: \\( \\lim_{x \\to 0} \\frac{\\sin 3x}{x} \\).', difficulty: 'easy', created_by: createdBy, status: '1', created_at: now },

    // Integral calculus questions
    { id: 107, exam_id: 1, stem: 'Evaluate \\( \\int x \\sin 2x \\, dx \\).', difficulty: 'medium', created_by: createdBy, status: '1', created_at: now },
    { id: 108, exam_id: 1, stem: 'Evaluate \\( \\int_0^{\\pi} \\sin x \\, dx \\).', difficulty: 'easy', created_by: createdBy, status: '1', created_at: now },
    { id: 109, exam_id: 1, stem: 'Evaluate \\( \\int e^x \\sin x \\, dx \\).', difficulty: 'hard', created_by: createdBy, status: '1', created_at: now },
    { id: 110, exam_id: 1, stem: 'Find the area enclosed by \\( y = x^2 \\) between \\( x=0 \\) and \\( x=2 \\).', difficulty: 'easy', created_by: createdBy, status: '1', created_at: now },
    { id: 111, exam_id: 1, stem: 'Evaluate \\( \\int_0^1 \\frac{dx}{1+x^2} \\).', difficulty: 'medium', created_by: createdBy, status: '1', created_at: now },
    { id: 112, exam_id: 1, stem: 'Find \\( \\frac{d}{dx} \\int_0^x \\sin t^2 \\, dt \\) at \\( x=0 \\).', difficulty: 'hard', created_by: createdBy, status: '1', created_at: now },
    { id: 113, exam_id: 1, stem: 'Find the volume generated by rotating area under \\( y=\\sqrt{x} \\), \\( 0 \\leq x \\leq 4 \\) about x-axis.', difficulty: 'medium', created_by: createdBy, status: '1', created_at: now },
    { id: 114, exam_id: 1, stem: 'Solve \\( \\int \\frac{dx}{x^2 - 1} \\).', difficulty: 'medium', created_by: createdBy, status: '1', created_at: now },
    { id: 118, exam_id: 1, stem: 'Evaluate \\( \\int \\frac{x}{\\sqrt{1 - x^2}} \\, dx \\).', difficulty: 'medium', created_by: createdBy, status: '1', created_at: now },
    { id: 121, exam_id: 1, stem: 'Evaluate \\( \\int \\cos^3 x \\, dx \\).', difficulty: 'medium', created_by: createdBy, status: '1', created_at: now },
    { id: 124, exam_id: 1, stem: 'Find \\( \\int_1^e \\frac{\\ln x}{x} \\, dx \\).', difficulty: 'medium', created_by: createdBy, status: '1', created_at: now },
    { id: 125, exam_id: 1, stem: 'Evaluate \\( \\int \\frac{1}{\\sqrt{x^2 + 4}} \\, dx \\).', difficulty: 'medium', created_by: createdBy, status: '1', created_at: now },
  ];

  await knex('questions').insert(questions);

  // Options for the above questions: four per question, one correct
  const options = [
    // Question 101
    { question_id: 101, option_text: '7', option_label: 'A', is_correct: true, status: '1', created_by: createdBy, created_at: now },
    { question_id: 101, option_text: '5', option_label: 'B', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 101, option_text: '6', option_label: 'C', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 101, option_text: '8', option_label: 'D', is_correct: false, status: '1', created_by: createdBy, created_at: now },

    // Question 102
    { question_id: 102, option_text: '1', option_label: 'A', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 102, option_text: '2', option_label: 'B', is_correct: true, status: '1', created_by: createdBy, created_at: now },
    { question_id: 102, option_text: '3', option_label: 'C', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 102, option_text: '0', option_label: 'D', is_correct: false, status: '1', created_by: createdBy, created_at: now },

    // Question 103
    { question_id: 103, option_text: 'Mass', option_label: 'A', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 103, option_text: 'Length', option_label: 'B', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 103, option_text: 'Speed', option_label: 'C', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 103, option_text: 'Impulse', option_label: 'D', is_correct: true, status: '1', created_by: createdBy, created_at: now },

    // Question 104
    { question_id: 104, option_text: 'True', option_label: 'A', is_correct: true, status: '1', created_by: createdBy, created_at: now },
    { question_id: 104, option_text: 'False', option_label: 'B', is_correct: false, status: '1', created_by: createdBy, created_at: now },

    // Question 105
    { question_id: 105, option_text: '60°', option_label: 'A', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 105, option_text: '90°', option_label: 'B', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 105, option_text: '120°', option_label: 'C', is_correct: true, status: '1', created_by: createdBy, created_at: now },
    { question_id: 105, option_text: '30°', option_label: 'D', is_correct: false, status: '1', created_by: createdBy, created_at: now },

    // Question 106
    { question_id: 106, option_text: '3', option_label: 'A', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 106, option_text: '1/2', option_label: 'B', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 106, option_text: '√14/2', option_label: 'C', is_correct: true, status: '1', created_by: createdBy, created_at: now },
    { question_id: 106, option_text: '5', option_label: 'D', is_correct: false, status: '1', created_by: createdBy, created_at: now },

    // Question 115
    { question_id: 115, option_text: '(0,0,0)', option_label: 'A', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 115, option_text: '(3,3,3)', option_label: 'B', is_correct: true, status: '1', created_by: createdBy, created_at: now },
    { question_id: 115, option_text: '(1,2,3)', option_label: 'C', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 115, option_text: '(4,5,6)', option_label: 'D', is_correct: false, status: '1', created_by: createdBy, created_at: now },

    // Question 116
    { question_id: 116, option_text: '5', option_label: 'A', is_correct: true, status: '1', created_by: createdBy, created_at: now },
    { question_id: 116, option_text: '7', option_label: 'B', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 116, option_text: '2', option_label: 'C', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 116, option_text: '8', option_label: 'D', is_correct: false, status: '1', created_by: createdBy, created_at: now },

    // Question 118
    { question_id: 118, option_text: '-√(1 - x^2) + C', option_label: 'A', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 118, option_text: '-√(1 - x^2)', option_label: 'B', is_correct: true, status: '1', created_by: createdBy, created_at: now },
    { question_id: 118, option_text: 'x^2/2 + C', option_label: 'C', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 118, option_text: 'ln|x + √(x^2 -1)| + C', option_label: 'D', is_correct: false, status: '1', created_by: createdBy, created_at: now },

    // Question 119
    { question_id: 119, option_text: '(6,3,2)', option_label: 'A', is_correct: true, status: '1', created_by: createdBy, created_at: now },
    { question_id: 119, option_text: '(3,6,2)', option_label: 'B', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 119, option_text: '(2,3,6)', option_label: 'C', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 119, option_text: '(1,1,1)', option_label: 'D', is_correct: false, status: '1', created_by: createdBy, created_at: now },

    // Question 120
    { question_id: 120, option_text: '3', option_label: 'A', is_correct: true, status: '1', created_by: createdBy, created_at: now },
    { question_id: 120, option_text: '0', option_label: 'B', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 120, option_text: '1', option_label: 'C', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 120, option_text: 'Undefined', option_label: 'D', is_correct: false, status: '1', created_by: createdBy, created_at: now },

    // Question 121
    { question_id: 121, option_text: 'sin x - (1/3) sin^3 x + C', option_label: 'A', is_correct: true, status: '1', created_by: createdBy, created_at: now },
    { question_id: 121, option_text: '-cos x + C', option_label: 'B', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 121, option_text: 'cos^3 x + C', option_label: 'C', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 121, option_text: 'sin^3 x + C', option_label: 'D', is_correct: false, status: '1', created_by: createdBy, created_at: now },

    // Question 124
    { question_id: 124, option_text: '( (ln e)^2 - (ln 1)^2 ) / 2', option_label: 'A', is_correct: true, status: '1', created_by: createdBy, created_at: now },
    { question_id: 124, option_text: '1/2', option_label: 'B', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 124, option_text: 'e', option_label: 'C', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 124, option_text: 'ln(e)', option_label: 'D', is_correct: false, status: '1', created_by: createdBy, created_at: now },

    // Question 125
    { question_id: 125, option_text: 'ln|x + sqrt(x^2 + 4)| + C', option_label: 'A', is_correct: true, status: '1', created_by: createdBy, created_at: now },
    { question_id: 125, option_text: 'arcsin(x/2) + C', option_label: 'B', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 125, option_text: 'sqrt(x^2 +4) + C', option_label: 'C', is_correct: false, status: '1', created_by: createdBy, created_at: now },
    { question_id: 125, option_text: 'x/2 + C', option_label: 'D', is_correct: false, status: '1', created_by: createdBy, created_at: now },
  ];

  // Insert options
  await knex('options').insert(options);
};
